### ISSUE TITLE
Use in Node.js

### ISSUE THREAD

**Issue by Vortec4800** [HQarroum/directed-graph#1]
This may be a dumb question, but I'm used to using libraries by adding them via npm. Is this available through npm? If not, how do I include it in my Node project? Can I just add the graph.js file to my project and ensure Underscore is in my package file? Looks like that's the only dependency.

**Comment by HQarroum** [comment]
Hi, thanks for your interest ! Yes this project is available through npm (https://www.npmjs.com/package/digraphe) and bower.

You are right I should have documented it in the README which [I just did](https://github.com/HQarroum/directed-graph/blob/master/README.md) :wink:

**Comment by Vortec4800** [comment]
Brilliant! Thanks!
